# Generated by Django 3.1.3 on 2020-11-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiration_date',
            new_name='expiry_date',
        ),
    ]
