# Generated by Django 3.1.3 on 2020-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0002_auto_20201124_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_gtin',
            field=models.BigIntegerField(),
        ),
    ]
